### ISSUE TITLE
Condense Soul Core Non functional

### ISSUE THREAD

**Issue by QuickenedPrism** [immortalityidle/immortalityidle.github.io#95] opened 2022-07-26 02:37 UTC
I have 3x Monster Gem Grade 14, and several gems of higher grades. I have a Spirituality of 5.4T. Condense Soul Core is current rank 2, but when I click the Condense Soul Core button, the interface closes, and the ascension is not performed.

Per Christian B on discord, created issue.

Save attached
[iigsave.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9186099/iigsave.txt)

**Comment by robostork** [comment] 2022-07-26 06:43
I'm having the same issue. Spirituality of 6.52T, condense soul core is rank 8, can't get to level 9. Same thing happens as QuickenedPrism when I try to ascend.

[save.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9187175/save.txt)

**Comment by kagejohn** [comment] 2022-07-26 07:46
For [QuickenedPrism](https://github.com/QuickenedPrism): i have no idea what the issue is it worked when i tried.
For [robostork](https://github.com/robostork): one of the checks need to be changed as your aptitudeGainDivider is 7.5(as it should be) and [the check won't let you upgrade if it is below 10](https://github.com/immortalityidle/immortalityidle.github.io/blob/cc8f8662d0b89012503be056a66af951f966de42/src/app/game-state/character.service.ts#L173)

**Comment by immortalityidle** [comment] 2022-07-26 17:32
The fix for robostork's issue is live on the experimental build, will be in the next version. For QuickenedPrism, when I import your save it doesn't have any problem with Condense Soul Core. Maybe refresh your browser to get the current version and try again. If that doesn't work, can you tell us what browser and version you are running?

**Closed** 2022-07-30 04:41 UTC
